### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/subl'

### ISSUE THREAD

**Issue by mccstan** [isis97/atom-terminal-panel#1013]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package 4.4.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/mccstan/subl'

```
At fs.js:115

Error: ENOENT: no such file or directory, stat '/Users/mccstan/subl'
    at statSync (fs.js:829:3)
    at Object.fs.statSync (ELECTRON_ASAR.js:284:27)
    at ATPOutputView.module.exports.ATPOutputView._fileInfoHtml (/packages/atom-terminal-panel/lib/atp-view.coffee:1081:19)
    at /packages/atom-terminal-panel/lib/atp-view.coffee:909:25
    at Array.forEach (<anonymous>)
    at ATPOutputView.module.exports.ATPOutputView.ls (/packages/atom-terminal-panel/lib/atp-view.coffee:908:11)
    at command (/packages/atom-terminal-panel/lib/atp-builtins-commands.coffee:25:20)
    at ATPOutputView.module.exports.ATPOutputView.exec_ (/packages/atom-terminal-panel/lib/atp-view.coffee:520:17)
    at ATPOutputView.module.exports.ATPOutputView.exec (/packages/atom-terminal-panel/lib/atp-view.coffee:456:13)
    at ATPOutputView.module.exports.ATPOutputView.onCommand (/packages/atom-terminal-panel/lib/atp-view.coffee:700:12)
    at /packages/atom-terminal-panel/lib/atp-view.coffee:193:8)
    at Object.call (/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:52:25)
    at Object.onEnter (/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:663:33)
    at HTMLInputElement.keyDownHandler (/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:885:11)
    at HTMLInputElement.dispatch (/packages/atom-terminal-panel/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/packages/atom-terminal-panel/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Non-Core Packages

```
atom-json 0.6.0 
atom-terminal-panel 4.4.4 
ide-json 0.2.1 
language-csv 1.1.2 
```

**Comment by mccstan** [comment]
Just remove this file : `rm ~/subl`
