### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/subl'

### ISSUE THREAD

**Issue by mccstan** [isis97/atom-terminal-panel#1014]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package 4.4.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/mccstan/subl'

```
At fs.js:115

Error: ENOENT: no such file or directory, stat '/Users/mccstan/subl'
    at statSync (fs.js:829:3)
    at Object.fs.statSync (ELECTRON_ASAR.js:284:27)
    at ATPOutputView.module.exports.ATPOutputView._fileInfoHtml (/packages/atom-terminal-panel/lib/atp-view.coffee:1081:19)
    at /packages/atom-terminal-panel/lib/atp-view.coffee:909:25
    at Array.forEach (<anonymous>)
    at ATPOutputView.module.exports.ATPOutputView.ls (/packages/atom-terminal-panel/lib/atp-view.coffee:908:11)
    at command (/packages/atom-terminal-panel/lib/atp-builtins-commands.coffee:25:20)
    at ATPOutputView.module.exports.ATPOutputView.exec_ (/packages/atom-terminal-panel/lib/atp-view.coffee:520:17)
    at ATPOutputView.module.exports.ATPOutputView.exec (/packages/atom-terminal-panel/lib/atp-view.coffee:456:13)
    at ATPOutputView.module.exports.ATPOutputView.onCommand (/packages/atom-terminal-panel/lib/atp-view.coffee:700:12)
    at /packages/atom-terminal-panel/lib/atp-view.coffee:193:8)
    at Object.call (/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:52:25)
    at Object.onEnter (/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:663:33)
    at HTMLInputElement.keyDownHandler (/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:885:11)
    at HTMLInputElement.dispatch (/packages/atom-terminal-panel/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/packages/atom-terminal-panel/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:32.5.0 command-palette:toggle (input.hidden-input)
 13x -3:29.5.0 core:backspace (input.hidden-input)
     -3:21.9.0 core:confirm (input.hidden-input)
     -3:21.9.0 settings-view:open (input.hidden-input)
     -0:25.3.0 command-palette:toggle (input.hidden-input)
     -0:20.7.0 core:confirm (input.hidden-input)
     -0:20.7.0 atom-terminal-panel:new (input.hidden-input)
     -0:15.7.0 core:confirm (div.panel.atp-panel.panel-bottom)
```

### Non-Core Packages

```
atom-terminal-panel 4.4.4 
blame 1.2.0 
rainbow-csv 1.0.0 
```

**Comment by mccstan** [comment]
Just remove this file : rm ~/subl
