### ISSUE TITLE
Failed to load package named 'atom-terminal-panel' Error: Cannot find module 'process'

### ISSUE THREAD

**Issue by simcha** [isis97/atom-terminal-panel#11]
After installing the package on Atom 0.174 (ubuntu linux) I have this error:
Failed to load package named 'atom-terminal-panel' Error: Cannot find module 'process'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/jtopinski/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:10:16)
  at Object.<anonymous> (/home/jtopinski/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:2:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/atom/resources/app/src/coffee-cache.js:65:19)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/jtopinski/.atom/packages/atom-terminal-panel/lib/cli-status-view.coffee:3:21)
  at Object.<anonymous> (/home/jtopinski/.atom/packages/atom-terminal-panel/lib/cli-status-view.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/atom/resources/app/src/coffee-cache.js:65:19)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/jtopinski/.atom/packages/atom-terminal-panel/lib/cli-status.coffee:1:17)
  at Object.<anonymous> (/home/jtopinski/.atom/packages/atom-terminal-panel/lib/cli-status.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/atom/resources/app/src/coffee-cache.js:65:19)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:623:34)
  at /usr/share/atom/resources/app/src/package.js:190:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:367:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:344:14)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:602:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:66:25)

/usr/share/atom/resources/app/src/package-manager.js:376 Could not resolve 'project-palette-finder' to a package path
/usr/share/atom/resources/app/src/package.js:240 Failed to activate package named 'atom-terminal-panel' Error: Cannot find module 'process'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/jtopinski/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:10:16)
  at Object.<anonymous> (/home/jtopinski/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:2:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/atom/resources/app/src/coffee-cache.js:65:19)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/jtopinski/.atom/packages/atom-terminal-panel/lib/cli-status-view.coffee:3:21)
  at Object.<anonymous> (/home/jtopinski/.atom/packages/atom-terminal-panel/lib/cli-status-view.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/atom/resources/app/src/coffee-cache.js:65:19)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/jtopinski/.atom/packages/atom-terminal-panel/lib/cli-status.coffee:1:17)
  at Object.<anonymous> (/home/jtopinski/.atom/packages/atom-terminal-panel/lib/cli-status.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/atom/resources/app/src/coffee-cache.js:65:19)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:623:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app/src/package.js:250:12)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:232:14)
  at /usr/share/atom/resources/app/src/package.js:221:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:453:21)
  at /usr/share/atom/resources/app/src/package-manager.js:434:29
  at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:344:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:428:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:411:46)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:605:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:66:25)

**Comment by isis97** [comment]
Thank you for reporting that bug, because forgot about broken requires. In the curent release (4.2.1) this problem was solved.

**Comment by simcha** [comment]
Thanks works for me now. Very nice package thanks.
