### ISSUE TITLE
Failed to load the atom-terminal-panel package

### ISSUE THREAD

**Issue by WebFreak001** [isis97/atom-terminal-panel#19]
1. Just by starting atom this happens

**Atom Version**: 0.189.0
**System**: Windows 8.1
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.4.1

### Stack Trace

Failed to load the atom-terminal-panel package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\Jan\AppData\Local\atom\app-0.189.0\resources\app\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at window.include (C:\Users\Jan\.atom\packages\atom-terminal-panel\lib\cli-utils.coffee:20:11)
    at Object.<anonymous> (C:\Users\Jan\.atom\packages\atom-terminal-panel\lib\command-output-view.coffee:36:30)
    at Object.<anonymous> (C:\Users\Jan\.atom\packages\atom-terminal-panel\lib\command-output-view.coffee:1786:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\Jan\AppData\Local\atom\app-0.189.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai-flat"
    ],
    "projectHome": "D:\\GitRepos\\",
    "autoHideMenuBar": true,
    "disabledPackages": [
      "preview-plus",
      "autocomplete",
      "autoflow"
    ]
  },
  "atom-terminal-panel": {}
}
```

### Installed Packages

```coffee
# User
atom-terminal-panel, v4.4.1
autocomplete-glsl, v0.2.1
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
linter, v0.12.1
linter-jshint, v0.1.2
linter-less, v0.3.1
linter-lua, v0.1.5
linter-tslint, v0.2.1
minimap, v4.7.6
monokai-flat, v1.0.1
script, v2.19.0
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by isis97** [comment]
Added missing dependencies, thank you. :)

**Comment by Stargator** [comment]
I am getting this with Atom.io 1.0.8 on Mac 10.10.5. It comes with the message: Cannot find module 'ansi-html-stream'

atom-terminal-panel 4.4.4
