### ISSUE TITLE
Uncaught Error: setTooltip is no longer available. Please use `atom.tooltips.add` instead.See the docs at https://atom.io/docs/api/latest/TooltipManager#instance-add

### ISSUE THREAD

**Issue by WebFreak001** [isis97/atom-terminal-panel#20]
1. Happens when doing `ls`

**Atom Version**: 0.189.0
**System**: Windows 8.1
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.4.2

### Stack Trace

Uncaught Error: setTooltip is no longer available. Please use `atom.tooltips.add` instead.
See the docs at https://atom.io/docs/api/latest/TooltipManager#instance-add

```
At C:\Users\Jan\AppData\Local\atom\app-0.189.0\resources\app\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:611

Error: setTooltip is no longer available. Please use `atom.tooltips.add` instead.
See the docs at https://atom.io/docs/api/latest/TooltipManager#instance-add
  at [object Object].$.fn.setTooltip (C:\Users\Jan\AppData\Local\atom\app-0.189.0\resources\app\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:611:11)
  at HTMLSpanElement.<anonymous> (C:\Users\Jan\.atom\packages\atom-terminal-panel\lib\command-output-view.coffee:826:21)
  at Function.jQuery.extend.each (C:\Users\Jan\AppData\Local\atom\app-0.189.0\resources\app\node_modules\jquery\dist\jquery.js:374:23)
  at [object Object].jQuery.fn.jQuery.each (C:\Users\Jan\AppData\Local\atom\app-0.189.0\resources\app\node_modules\jquery\dist\jquery.js:139:17)
  at CommandOutputView.module.exports.CommandOutputView.parseSpecialNodes (C:\Users\Jan\.atom\packages\atom-terminal-panel\lib\command-output-view.coffee:823:48)
  at CommandOutputView.module.exports.CommandOutputView.message (C:\Users\Jan\.atom\packages\atom-terminal-panel\lib\command-output-view.coffee:1168:6)
  at CommandOutputView.module.exports.CommandOutputView.message (C:\Users\Jan\.atom\packages\atom-terminal-panel\lib\command-output-view.coffee:1156:10)
  at CommandOutputView.module.exports.CommandOutputView.ls (C:\Users\Jan\.atom\packages\atom-terminal-panel\lib\command-output-view.coffee:816:6)
  at module.exports.ls.command (C:\Users\Jan\.atom\packages\atom-terminal-panel\lib\cli-builtins-commands.coffee:26:20)
  at CommandOutputView.module.exports.CommandOutputView.exec_ (C:\Users\Jan\.atom\packages\atom-terminal-panel\lib\command-output-view.coffee:419:17)
  at CommandOutputView.module.exports.CommandOutputView.exec (C:\Users\Jan\.atom\packages\atom-terminal-panel\lib\command-output-view.coffee:355:13)
  at CommandOutputView.module.exports.CommandOutputView.onCommand (C:\Users\Jan\.atom\packages\atom-terminal-panel\lib\command-output-view.coffee:587:12)
  at HTMLDivElement.<anonymous> (C:\Users\Jan\.atom\packages\atom-terminal-panel\lib\command-output-view.coffee:146:11)
  at HTMLDivElement.jQuery.event.dispatch (C:\Users\Jan\AppData\Local\atom\app-0.189.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at HTMLDivElement.elemData.handle (C:\Users\Jan\AppData\Local\atom\app-0.189.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
     -0:34.9 core:move-down (atom-text-editor.editor)
     -0:34.4 core:select-left (atom-text-editor.editor)
     -0:32.8 core:move-down (atom-text-editor.editor)
     -0:32.6 core:select-left (atom-text-editor.editor)
  8x -0:31.2 core:move-left (atom-text-editor.editor)
  3x -0:30.0 core:select-right (atom-text-editor.editor)
  9x -0:29.3 find-and-replace:select-next (atom-text-editor.editor)
  2x -0:25.4 core:move-right (atom-text-editor.editor)
     -0:24.7 editor:move-to-end-of-word (atom-text-editor.editor)
     -0:24.3 core:move-right (atom-text-editor.editor)
     -0:23.6 core:select-right (atom-text-editor.editor)
     -0:20.2 core:delete (atom-text-editor.editor)
     -0:19.5 core:move-right (atom-text-editor.editor)
     -0:19.2 editor:newline (atom-text-editor.editor)
     -0:18.2 core:move-left (atom-text-editor.editor)
  7x -0:17.8 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai-flat"
    ],
    "projectHome": "D:\\GitRepos\\",
    "autoHideMenuBar": true,
    "disabledPackages": [
      "preview-plus",
      "autocomplete",
      "autoflow"
    ]
  },
  "atom-terminal-panel": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.1
atom-terminal-panel, v4.4.2
autocomplete-glsl, v0.2.1
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
language-d, v3.1.2
language-ejs, v0.1.0
language-glsl, v2.0.0
language-ini, v1.10.0
language-jade, v0.4.0
language-lua, v0.9.2
language-typescript, v0.15.0
linter, v0.12.1
linter-jshint, v0.1.2
linter-less, v0.3.1
linter-lua, v0.1.5
linter-tslint, v0.2.1
minifier, v0.2.0
minimap, v4.7.6
monokai-flat, v1.0.1
script, v2.19.0
seti-ui, v0.6.3
Stylus, v1.0.0

# Dev
No dev packages
```

**Comment by Rask** [comment]
+1, just installed and breaks the usage flow because of this issue.

**Comment by CristyTarantino** [comment]
+1

**Comment by isis97** [comment]
Bug removed. Thanks. :smile:
