### ISSUE TITLE
Uncaught Error: setTooltip is no longer available. Please use `atom.tooltips.add` instead.See the docs at https://atom.io/docs/api/latest/TooltipManager#instance-add

### ISSUE THREAD

**Issue by squizduos** [isis97/atom-terminal-panel#22]
[Enter steps to reproduce below:]

1. Press ctrl+shift
2. Write ls to opened terminal
3. Press Enter

**Atom Version**: 0.194.0
**System**: linux 3.16.0-34-generic
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.4.2

### Stack Trace

Uncaught Error: setTooltip is no longer available. Please use `atom.tooltips.add` instead.
See the docs at https://atom.io/docs/api/latest/TooltipManager#instance-add

```
At /usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:611

Error: setTooltip is no longer available. Please use `atom.tooltips.add` instead.
See the docs at https://atom.io/docs/api/latest/TooltipManager#instance-add
    at $.fn.setTooltip (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:611:11)
    at HTMLSpanElement.<anonymous> (/home/squizduos/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:1211:28)
    at Function.jQuery.extend.each (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:374:23)
    at jQuery.fn.jQuery.each (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:139:17)
    at CommandOutputView.module.exports.CommandOutputView.parseSpecialNodes (/home/squizduos/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:1207:50)
    at CommandOutputView.module.exports.CommandOutputView.message (/home/squizduos/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:1672:12)
    at CommandOutputView.module.exports.CommandOutputView.message (/home/squizduos/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:1661:16)
    at CommandOutputView.module.exports.CommandOutputView.ls (/home/squizduos/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:1199:12)
    at module.exports.ls.command (/home/squizduos/.atom/packages/atom-terminal-panel/lib/cli-builtins-commands.coffee:34:20)
    at CommandOutputView.module.exports.CommandOutputView.exec_ (/home/squizduos/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:646:19)
```

### Commands

```
     -0:02.3.0 atom-terminal-panel:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "SFTP-deployment",
      "atom-django"
    ]
  },
  "atom-terminal-panel": {}
}
```

### Installed Packages

```coffee
# User
atom-terminal-panel, v4.4.2
autocomplete-plus, v2.12.0
autocomplete-plus-python-jedi, v0.2.7
django-templates, v0.4.0
language-django, v0.1.1

# Dev
No dev packages
```

**Comment by isis97** [comment]
This is being resolved.
