### ISSUE TITLE
Failed to activate the atom-terminal-panel package

### ISSUE THREAD

**Issue by chrisnesbit1** [isis97/atom-terminal-panel#26]
[Enter steps to reproduce below:]

1. already had this package installed, but disabled.
2. auto-updated to the new version of atom this morning
3. enabled this package after the auto-update

**Atom Version**: 0.198.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.4.3

### Stack Trace

Failed to activate the atom-terminal-panel package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.activate (/Users/chrisnesbit/.atom/packages/atom-terminal-panel/lib/cli-status.coffee:24:21)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:242:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:223:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:303:19
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:152:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:132:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:252:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -0:59.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:57.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:57.2.0 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "remote-atom",
      "term",
      "terminal-panel",
      "term2",
      "atom-beautify",
      "lesscompile",
      "feedback",
      "open-on-github",
      "timecop",
      "terminal-runner",
      "useful-context-menu",
      "terminal-status",
      "language-clojure",
      "language-coffee-script",
      "run-command",
      "run-command2",
      "commands",
      "run-in-terminal",
      "browser-plus",
      "script-runner",
      "command-toolbar",
      "language-mustache",
      "archive-view",
      "autoflow",
      "background-tips",
      "bookmarks",
      "deprecation-cop",
      "whitespace",
      "fuzzy-finder",
      "welcome"
    ]
  },
  "atom-terminal-panel": {
    "logConsole": true,
    "enableWindowAnimations": false,
    "overrideLs": false
  }
}
```

### Installed Packages

```coffee
# User
atom-terminal-panel, v4.4.3
git-diff-details, v0.18.0
git-projects, v1.13.0
go-format, v1.0.7
pdf-view, v0.22.0

# Dev
No dev packages
```

**Comment by isis97** [comment]
Bug repaired in the new version. Thanks for noting that.
