### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by MLourensMoog** [isis97/atom-terminal-panel#35]
[Enter steps to reproduce below:]

1. Just opened the terminal pane with the little icon at the bottom of the screen

**Atom Version**: 0.199.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.4.4

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\mlourens\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:178

TypeError: undefined is not a function
  at ATPOutputView.module.exports.ATPOutputView.putInputBox (C:\Users\mlourens\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:178:37)
  at ATPOutputView.module.exports.ATPOutputView.open (C:\Users\mlourens\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:822:6)
  at ATPOutputView.module.exports.ATPOutputView.toggle (C:\Users\mlourens\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:868:8)
  at HTMLSpanElement.<anonymous> (C:\Users\mlourens\.atom\packages\atom-terminal-panel\lib\atp-panel.coffee:86:25)
  at HTMLSpanElement.jQuery.event.dispatch (C:\Users\mlourens\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLSpanElement.elemData.handle (C:\Users\mlourens\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -2:52.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
  4x -2:20.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "welcome",
      "wrap-guide",
      "timecop",
      "atom-angularjs"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "audioBeep": false
  },
  "atom-terminal-panel": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-terminal-panel, v4.4.4
grunt-runner, v0.9.1
jsformat, v0.8.1

# Dev
No dev packages
```

**Comment by danopia** [comment]
Just invoked for me, and threw a new error every time I saved a file
