### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\Bruno\Ambiente de Impressão'

### ISSUE THREAD

**Issue by brunofreitas7** [isis97/atom-terminal-panel#48]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Unknown Windows Version
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.4.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\Bruno\Ambiente de Impressão'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat 'C:\Users\Bruno\Ambiente de Impressão'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at ATPOutputView.module.exports.ATPOutputView._fileInfoHtml (C:\Users\Bruno\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:1081:19)
  at C:\Users\Bruno\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:909:25
  at Array.forEach (native)
  at ATPOutputView.module.exports.ATPOutputView.ls (C:\Users\Bruno\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:908:11)
  at module.exports.ls.command (C:\Users\Bruno\.atom\packages\atom-terminal-panel\lib\atp-builtins-commands.coffee:25:20)
  at ATPOutputView.module.exports.ATPOutputView.exec_ (C:\Users\Bruno\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:520:17)
  at ATPOutputView.module.exports.ATPOutputView.exec (C:\Users\Bruno\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:456:13)
  at ATPOutputView.module.exports.ATPOutputView.onCommand (C:\Users\Bruno\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:700:12)
  at Object.<anonymous> (C:\Users\Bruno\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:193:8)
  at Object.call (C:\Users\Bruno\.atom\packages\atom-terminal-panel\node_modules\jquery-autocomplete-js\autocomplete.js:52:25)
  at Object.rs.onEnter (C:\Users\Bruno\.atom\packages\atom-terminal-panel\node_modules\jquery-autocomplete-js\autocomplete.js:663:33)
  at HTMLInputElement.keyDownHandler (C:\Users\Bruno\.atom\packages\atom-terminal-panel\node_modules\jquery-autocomplete-js\autocomplete.js:885:11)
  at HTMLInputElement.jQuery.event.dispatch (C:\Users\Bruno\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLInputElement.elemData.handle (C:\Users\Bruno\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
  4x -5:31 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:20.5.0 editor:outdent-selected-rows (atom-text-editor.editor.mini.is-focused)
     -3:29.7.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -3:26.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:20.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -3:19.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:28.5.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-terminal-panel, v4.4.4

# Dev
No dev packages
```

**Comment by mccstan** [comment]
Remove the mentionned folder and you're good to go
