### ISSUE TITLE
Uncaught ReferenceError: fs is not defined

### ISSUE THREAD

**Issue by QuantCare** [isis97/atom-terminal-panel#70]
Reproduce with:
> rm path/to/file

**Atom Version**: 1.0.11
**System**: Ubuntu 14.04.3
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.4.4

### Stack Trace

Uncaught ReferenceError: fs is not defined

```
At /home/user/.atom/packages/atom-terminal-panel/lib/atp-builtins-commands.coffee:73

ReferenceError: fs is not defined
    at module.exports.rm.command (/home/user/.atom/packages/atom-terminal-panel/lib/atp-builtins-commands.coffee:73:7)
    at ATPOutputView.module.exports.ATPOutputView.exec_ (/home/user/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:520:17)
    at ATPOutputView.module.exports.ATPOutputView.exec (/home/user/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:456:13)
    at ATPOutputView.module.exports.ATPOutputView.onCommand (/home/user/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:700:12)
    at Object.<anonymous> (/home/user/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:193:8)
    at Object.call (/home/user/.atom/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:52:25)
    at Object.rs.onEnter (/home/user/.atom/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:663:33)
    at HTMLInputElement.keyDownHandler (/home/user/.atom/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:885:11)
    at HTMLInputElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:08.7.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
     -0:08.4.0 atom-terminal-panel:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-terminal-panel, v4.4.4
atom-typescript, v6.0.0
build, v0.44.0
linter, v1.4.3

# Dev
No dev packages
```

**Comment by DavidBock** [comment]
Same, reproduced with:

> new filename
