### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toggle' of undefined

### ISSUE THREAD

**Issue by tkhosravi** [isis97/atom-terminal-panel#75]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.4.4

### Stack Trace

Uncaught TypeError: Cannot read property 'toggle' of undefined

```
At /Users/tkhosravi/.atom/packages/atom-terminal-panel/lib/atp-panel.coffee:156

TypeError: Cannot read property 'toggle' of undefined
  at ATPPanel.module.exports.ATPPanel.toggle (/Users/tkhosravi/.atom/packages/atom-terminal-panel/lib/atp-panel.coffee:156:32)
  at atom-workspace.atom.commands.add.atom-terminal-panel:toggle (/Users/tkhosravi/.atom/packages/atom-terminal-panel/lib/atp-panel.coffee:42:41)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/src/command-registry.js:143:19)
  at EventEmitter.module.exports.WindowEventHandler.handleIPCCommand (/opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:213:28)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
  2x -5:35.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  3x -5:35.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
 11x -5:34.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:26.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:26.6.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
  6x -5:25.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:18.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -4:37.8.0 terminal-panel:new (atom-text-editor.editor.mini.is-focused)
  2x -3:08.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:04.4.0 turbo-javascript:end-line-comma (atom-text-editor.editor.is-focused)
  7x -3:02.3.0 core:undo (atom-text-editor.editor.is-focused)
  3x -2:52.9.0 core:redo (atom-text-editor.editor.is-focused)
     -2:36.2.0 terminal-panel:toggle (atom-text-editor.editor.is-focused)
     -2:20.8.0 terminal-panel:next (atom-text-editor.editor.is-focused)
     -2:12.2.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
     -0:01.5.0 atom-terminal-panel:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-terminal-panel, v4.4.4
color-picker, v2.0.13
jsformat, v0.9.0
linter, v1.10.0
linter-jshint, v1.2.1
term2, v0.9.21
terminal-panel, v1.14.1
turbo-javascript, v1.2.0

# Dev
No dev packages
```

**Comment by oswaldoferreira** [comment]
+1

**Comment by joaoscotto** [comment]
**Atom Version**: 1.7.3
**System**: Unknown Windows Version
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.4.4


### Stack Trace

Uncaught TypeError: Cannot read property 'toggle' of undefined

```
At /C:/Users/joao/.atom/packages/atom-terminal-panel/lib/atp-panel.coffee:307

TypeError: Cannot read property 'toggle' of undefined
    at ATPPanel.module.exports.ATPPanel.toggle (file:///C:/Users/joao/.atom/packages/atom-terminal-panel/lib/atp-panel.coffee:156:32)
    at ATPPanel.module.exports.ATPPanel.getForcedActiveCommandView (file:///C:/Users/joao/.atom/packages/atom-terminal-panel/lib/atp-panel.coffee:119:6)
    at ATPPanel.module.exports.ATPPanel.runInCurrentView (file:///C:/Users/joao/.atom/packages/atom-terminal-panel/lib/atp-panel.coffee:110:10)
    at atom-workspace.atom.commands.add.atom-terminal-panel:toggle-autocompletion (file:///C:/Users/joao/.atom/packages/atom-terminal-panel/lib/atp-panel.coffee:49:56)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\joao\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\joao\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\joao\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\joao\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\joao\AppData\Local\atom\app-1.7.3\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\joao\AppData\Local\atom\app-1.7.3\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -2:48.1.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
     -0:09.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:09.6.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:09.2.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:08.3.0 core:delete (atom-text-editor.editor.is-focused)
     -0:06.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:05.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:04.9.0 core:delete (atom-text-editor.editor.is-focused)
     -0:04.1.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
     -0:03.9.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-terminal-panel, v4.4.4

# Dev
No dev packages
```
