### ISSUE TITLE
Uncaught Error: Cannot find module 'ps-tree'

### ISSUE THREAD

**Issue by ghost** [isis97/atom-terminal-panel#889]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package 4.4.4

### Stack Trace

Uncaught Error: Cannot find module 'ps-tree'

```
At module.js:545

Error: Cannot find module 'ps-tree'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.38.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:11:146462)
    at ATPOutputView.module.exports.ATPOutputView.terminateProcessTree (/packages/atom-terminal-panel/lib/atp-view.coffee:769:14)
    at ATPOutputView.module.exports.ATPOutputView.kill (/packages/atom-terminal-panel/lib/atp-view.coffee:798:8)
    at /packages/atom-terminal-panel/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/atom-terminal-panel/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/atom-terminal-panel/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -1:24.3.0 core:cut (div.panel.atp-panel.panel-bottom)
     -1:24 core:undo (div.panel.atp-panel.panel-bottom)
     -1:24 core:cut (div.panel.atp-panel.panel-bottom)
  4x -0:33.5.0 core:confirm (div.panel.atp-panel.panel-bottom)
     -0:26.2.0 core:move-down (div.panel.atp-panel.panel-bottom)
  2x -0:25.7.0 core:confirm (div.panel.atp-panel.panel-bottom)
  3x -0:23.8.0 atom-terminal-panel:toggle-autocompletion (div.panel.atp-panel.panel-bottom)
     -0:20.9.0 core:undo (div.panel.atp-panel.panel-bottom)
     -0:20.9.0 core:cut (div.panel.atp-panel.panel-bottom)
     -0:20.7.0 core:undo (div.panel.atp-panel.panel-bottom)
     -0:20.7.0 core:cut (div.panel.atp-panel.panel-bottom)
  2x -0:20.6.0 atom-terminal-panel:toggle-autocompletion (div.panel.atp-panel.panel-bottom)
     -0:20.5.0 core:undo (div.panel.atp-panel.panel-bottom)
     -0:20.4.0 core:cut (div.panel.atp-panel.panel-bottom)
     -0:20.2.0 atom-terminal-panel:toggle-autocompletion (div.panel.atp-panel.panel-bottom)
  5x -0:19.8.0 core:confirm (div.panel.atp-panel.panel-bottom)
```

### Non-Core Packages

```
atom-live-server 2.3.0 
atom-terminal-panel 4.4.4 
teletype 0.13.4 
```

**Comment by ghost** [comment]
can`t kill process for started mongodb
