### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by MonstroDev** [isis97/atom-terminal-panel#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.181.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/vasyasemenov/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:843

TypeError: Cannot read property 'replace' of undefined
  at CommandOutputView.module.exports.CommandOutputView.removeQuotes (/Users/vasyasemenov/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:843:16)
  at CommandOutputView.module.exports.CommandOutputView.removeQuotes (/Users/vasyasemenov/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:841:20)
  at CommandOutputView.module.exports.CommandOutputView.cd (/Users/vasyasemenov/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:847:13)
  at module.exports.CommandOutputView.localCommands.cd.command (/Users/vasyasemenov/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:85:40)
  at CommandOutputView.module.exports.CommandOutputView.exec (/Users/vasyasemenov/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:547:17)
  at CommandOutputView.module.exports.CommandOutputView.onCommand (/Users/vasyasemenov/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:712:12)
  at HTMLDivElement.<anonymous> (/Users/vasyasemenov/.atom/packages/atom-terminal-panel/lib/command-output-view.coffee:197:11)
  at HTMLDivElement.handler (/Users/vasyasemenov/Downloads/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDivElement.jQuery.event.dispatch (/Users/vasyasemenov/Downloads/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (/Users/vasyasemenov/Downloads/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -3:03.7 pane:reopen-closed-item (atom-text-editor.editor)
  9x -0:20.8 atom-terminal-panel:toggle (atom-text-editor.editor)
  8x -0:05.0 core:focus-next (input.terminal-input.native-key-bindings)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "linter-rubocop"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-angularjs, v0.1.2
atom-browser-webview, v0.6.0
atom-lint, v0.20.1
atom-terminal-panel, v4.1.2
auto-update-packages, v0.2.2
coffee-navigator, v0.0.15
coffee-refactor, v0.6.2
emmet, v2.3.3
file-icons, v1.4.11
language-coffee-script, v0.39.0
language-coffee-script-angular, v2.2.0
language-haml, v0.15.0
language-json, v0.12.0
language-powershell, v1.0.0
language-ruby, v0.48.0
language-ruby-on-rails, v0.19.0
language-scala, v1.1.0
linter, v0.11.1
linter-erb, v0.1.0
localization, v1.16.1
notifications, v0.28.0
react, v0.9.9
refactor, v0.4.1

# Dev
No dev packages
```

**Comment by isis97** [comment]
Thank you for reporting that.

**Comment by isis97** [comment]
This should never happen in the recent release. If this problem repeats please leave a proper message.
